import os
import numpy as np
from PIL import Image
import cv2
import math


if __name__ == "__main__":
    output_path = [
        "story_utils/stories/sketch_1.png",
        "story_utils/stories/sketch_2.png",
        "story_utils/stories/sketch_3.png",
        "story_utils/stories/sketch_4.png",
        "story_utils/stories/sketch_5.png",
        "story_utils/stories/sketch_6.png",
        "story_utils/stories/sketch_7.png",
        ]
    height, width = 512, 1024
    
    # PATH of sketches generated by pidinet
    input_subject_dict = [
        {
            "sketch_path": [
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/1/eval_results/imgs_epoch_019/mask.png",
            ],
            "box_layout": [
                [0.339453125, 0.161328125, 0.9138671875, 0.969140625],
            ],
        },
        {
            "sketch_path": [
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/2/eval_results/imgs_epoch_019/mask.png",
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/3/eval_results/imgs_epoch_019/mask.png",
            ],
            "box_layout": [
                [0.408828125, 0.1, 0.990234375, 0.997265625], [0.169921875, 0.255859375, 0.4591796875, 0.754375],
            ],
        },
        {
            "sketch_path": [
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/4/eval_results/imgs_epoch_019/mask.png",
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/5/eval_results/imgs_epoch_019/mask.png",
            ],
            "box_layout": [
                [0.2392578125, 0.251953125, 0.5087890625, 0.763671875],[0.5064453125, 0.103984375, 0.95296875, 0.862109375],
            ],
        },
        {
            "sketch_path": [
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/6/eval_results/imgs_epoch_019/mask.png",
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/7/eval_results/imgs_epoch_019/mask.png",
            ],
            "box_layout": [
                [0.1158203125, 0.253515625, 0.490234375, 0.734375], [0.50640625, 0.234375, 0.879296875, 0.70546875],
            ],
        },
        {
            "sketch_path": [
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/8/eval_results/imgs_epoch_019/mask.png",
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/9/eval_results/imgs_epoch_019/mask.png",
            ],
            "box_layout": [
                [0.228515625, 0.3515625, 0.5625, 0.9296875], [0.640625, 0.2734375, 0.89453125, 0.90625],
            ],
        },
        {
            "sketch_path": [
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/10/eval_results/imgs_epoch_019/mask.png",
                "/mnt/nas/share/home/canyu/Diffusion/STORY/ours_region/pidinet/savedir/11/eval_results/imgs_epoch_019/mask.png",
            ],
            "box_layout": [
                [0.058203125, 0.16796875, 0.4462890625, 0.993046875], [0.505859375, 0.203125, 0.802734375, 0.880859375],
            ],
        },
    ]
    table = []
    for i in range(256):
        if i < 10:
            table.append(0)
        else:
            table.append(1)

    # draw the subject
    ind = 0
    for sub in input_subject_dict:
        # create a black image
        img = np.zeros((height, width), np.uint8)
        subject_path_list = sub["sketch_path"]
        box_layout_list = sub["box_layout"]
        for subject_path, box_layout in zip(subject_path_list, box_layout_list):
            # get the subject size
            x0, y0, x1, y1 = box_layout
            # use ceil for x0 and y0, following mixofshow
            x0, y0, x1, y1 = math.ceil(x0 * width), math.ceil(y0 * height), int(x1 * width), int(y1 * height)
            subject_width = x1 - x0
            subject_height = y1 - y0

            # load image with PIL
            subject_img = Image.open(subject_path)
            subject_img = subject_img.resize((subject_width, subject_height))  # TODO we should keep aspect ratio
            subject_img = np.array(subject_img)

            # draw the subject
            img[y0:y1, x0:x1] = subject_img
        
        kernel = np.ones((3,3),np.uint8) 
        dilation = cv2.dilate(img,kernel,iterations = 1)
        
        img = Image.fromarray(dilation).convert('L')
        
        img = img.point(table, '1')
        img.save(output_path[ind])
        ind +=1
        input()
